### ISSUE TITLE
Code for models

### ISSUE THREAD

**Issue by akashrajkn** [google-research/seanet#1]
Will you be releasing the code for SEAnet and MicAugment in the future?

**Comment by josephrocca** [comment]
Hey @pen-li, is it safe to assume that this repo is just for audio samples and the code/models aren't going to be released publicly?

**Comment by pen-li** [comment]
Yes, that's exactly right. Only audio samples and no code models, as this
repo is intended to serve.

**Comment by josephrocca** [comment]
@pen-li Okay, thanks for your reply! Just to confirm, there are no plans to release any of the models (even in another repo, I mean)?

**Comment by pen-li** [comment]
That's correct. No such plans at the moment.

**Comment by josephrocca** [comment]
Okay, thanks for letting us know. I think this issue can be closed then.

**Comment by akashrajkn** [comment]
Thanks for the reply! I'll close this issue.
